// Code generated by github.com/emicklei/cmd/nls. DO NOT EDIT.

package nls

import (
	NLS "github.com/emicklei/nls"
)

const (
	M_cats = "cats"
	// M_hello is for a friendly greeting
	M_hello = "hello"
	M_multi = "multi"
	M_sea = "sea"
	M_sky = "sky"
	M_world = "world"
)

// all messages found in all language folders
var messages = map[string]string{
	"en." + M_multi: `{{.name}} says hello
to the world
`,
	"en." + M_sea: `{{.color }} sea`,
	"en." + M_sky: `Sky`,
	"en." + M_world: `world`,
	"en." + M_cats: `{{.count}} {{- if gt .count 1}} cats{{- else}} cat{{- end}}`,
	"en." + M_hello: `hello`,
	"nl." + M_world: `wereld`,
	"nl." + M_cats: `{{.count}} {{- if gt .count 1}} katten{{- else}} kat{{- end}}`,
	"nl." + M_hello: `hallo`,
	"nl." + M_multi: `{{.name}} zegt hallo
tegen de wereld
`,
	"nl." + M_sea: `{{.name }} zee`,
}

// New returns a Localizer with zero or more languages.
func New(languages ...string) NLS.Localizer {
	return NLS.NewLocalizer(messages, languages...)
}
